services:
  - type: web
    name: jurnalsiswa
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: APP_NAME
        value: JurnalSiswa
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://jurnalsiswa.onrender.com
      - key: ASSET_URL
        value: https://jurnalsiswa.onrender.com
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: r2
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_AUTH_TOKEN
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_URL
        sync: false
      - key: R2_REGION
        value: auto
